
Vagrant.configure("2") do |config|
 config.vm.define "applicationServer" do |applicationServer|
  config.vm.box = "almalinux/9"
  config.vm.hostname = "applicationserver"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "application"
    vb.memory = 2048
    vb.cpus = 2
  end
  applicationServer.vm.network "private_network",
  ip: "192.168.100.10",
  virtualbox__intnet: "intnet"
  applicationServer.vm.synced_folder "./provisioning","/mnt/provisioning"
  applicationServer.vm.provision "shell",
    path: "./provisioning/applicationServer.sh",
    run: "always"
end


#client 
config.vm.define "client" do |client|
  client.vm.box = "bento/debian-12"
  client.vm.hostname = "client"
  client.vm.network "private_network", ip: "192.168.100.11",
  virtualbox__intnet: "intnet"

  client.vm.provider "virtualbox" do |vb|
    vb.name = "gui-client"
    vb.gui = true
    vb.memory = 2048
    vb.cpus = 2
    vb.customize ["modifyvm", :id, "--vram", "64"]
    vb.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
  end

  client.vm.provision "shell", inline: <<-SHELL
    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    apt-get install -y xfce4 lightdm firefox-esr
    systemctl set-default graphical.target
    reboot
  SHELL
end
end
